### ISSUE TITLE
maybe about some animations

### ISSUE THREAD

**Issue by jinjilynn** [subhamayd2/day_night_time_picker#41]
I set up a controlled widget wrapping the picker to controll its value and i occurs below error:

![image](https://user-images.githubusercontent.com/12596042/147333015-fd91e81b-d4f7-43a9-97ef-5fdfbae77ea2.png)

**Comment by TheGlorySaint** [comment]
@jinjilynn sadly this project seems not to be maintained anymore. I have fixed that issue but the pull requests is not getting merged. You can use my Pullrequests in your pubspec.yaml file and this fixes your issue.

```
day_night_time_picker:
   git:
    url: https://github.com/TheGlorySaint/day_night_time_picker.git
    ref: Issue_38_fixing_setSate
```
