### ISSUE TITLE
Does not work in Flutter 3.0

### ISSUE THREAD

**Issue by md-siam** [subhamayd2/day_night_time_picker#60]
This repo is unsupported in Flutter 3.0

Please fix it. 

Thanks

**Comment by TheGlorySaint** [comment]
Hello @md-siam,

we added support for flutter 3.0, the Package will be soon updated at pub dev

**Comment by JulianBissekkou** [comment]
Do you know when you will release the flutter 3.0 fixes to pub?

**Comment by TheGlorySaint** [comment]
Hi @JulianBissekkou,

Sadly, I'm only a contributor/maintainer of this package and do not have access to manage the pub.dev account and with this the Release. I have already contacted the owner of the pub.dev account and asked for a new Release, currently i have nothing heared.

**Comment by md-siam** [comment]
I had to replace this package from my application. 😮‍💨

**Comment by JulianBissekkou** [comment]
@TheGlorySaint Thanks for the update! :) 

@md-siam You can just use the package from the current main/develop branch of this repository. 
```yml
day_night_time_picker:
    git:
      url: git://github.com:subhamayd2/day_night_time_picker.git
      ref: develop
```
